api/urls.py
from django.urls import path,include
from rest_framework import routers
from api.views import StandardViewSet,SubjectViewSet,LessonViewSet,UserViewSet

router=routers.DefaultRouter()
router.register(r'users',UserViewSet)
router.register(r'standards', StandardViewSet, basename='standard')
router.register(r'subjects', SubjectViewSet,basename='subject')
router.register(r'lessons', LessonViewSet,basename='lesson')

urlpatterns = [
    path('', include(router.urls)),
]

curriculum/urls.py
from django.urls import path,include
from . import views

app_name='curriculum'
urlpatterns = [
    path('training_level/',views.training_level, name="training_level"),
    path('trainer_subject_1/',views.trainer_subject_1, name="trainer_subject_1"),
    path('trainer_subject_2/',views.trainer_subject_2, name="trainer_subject_2"),
    path('trainer_subject_3/',views.trainer_subject_3, name="trainer_subject_3"),
    path('trainer_lesson/<slug:slug>',views.trainer_lesson,name="trainer_lesson"),
    path('mentor/level/', views.mentor_training_level, name='mentor_training_level'),
    path('mentor/subjects/<str:level>/', views.mentor_subjects_by_level, name='mentor_subjects_by_level'),
    path('mentor/lessons/<slug:subject_slug>/<module>/', views.mentor_lesson_by_module, name='mentor_lesson_by_module'),
    path('mentor/lesson/<slug:slug>/', views.mentor_lesson_detail, name='mentor_lesson_detail'),
    path('rate-lecture/', views.LectureRatingCreateView.as_view(), name='rate-lecture'),
    path("trainer_lesson_detail/<slug:slug>",views.trainer_lesson_detail, name="trainer_lesson_detail"),
    path('coding/', views.coding, name="coding"),
    path('codinglessons/<slug:slug>/',views.codinglessons,name="codinglessons"),
    path('codinglesson_detail/<slug:slug>/',views.codinglesson_detail, name="codinglesson_detail"),
    path('ai/',views.ai,name="ai"),
    path('lessons/<slug:slug>/',views.lessons,name="lessons"),
    path('lesson_detail/<slug:slug>/',views.lesson_detail, name="lesson_detail"),
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),
    # path("mechanzo_kits/", views.display_kits, name="mechanzo_kits"),
    # path("<slug:slug>/", views.display_models, name="models_list")
]

ebook/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('grades/', views.grade_list, name='grade_list'),
    path('grades/<int:grade_id>/books/', views.ebook_list, name='ebook_list'),
    path('books/<int:book_id>/lessons/', views.display_lessons, name='display_lessons'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('curriculum/', include(('curriculum.urls','curriculum'), namespace='curriculum')),
    path('mechanzo/', include(('mechanzo.urls','mechanzo'),namespace="mechanzo")),
    # path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('ebook/', include(('ebook.urls', 'ebook'), namespace='ebook')),
    path('', include('pwa.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

mechanzo/urls.py
from django.urls import path,include
from . import views

app_name='mechanzo'
urlpatterns = [
    path("", views.display_kits, name="mechanzo_kits"),
    path("<slug:slug>/", views.display_models, name="models_list")
]

users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from users.utils import activate
from . import StudentViews
from . import SchoolView,PrincipalView,TeacherView

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('student/', views.StudentSignUpView.as_view(), name="user_student"),
    path('parent/', views.ParentSignUpView.as_view(), name="user_parent"),
    path('teacher/', views.TeacherSignUpView.as_view(), name="user_teacher"),
    path('principal/', views.PrincipalSignUpView.as_view(), name="user_principal"),
    path('school/', views.SchoolSignUpView.as_view(), name="user_school"),
    path('students_registration/',views.register_student_from_excel, name="students_registration"),
    path('download-excel-template/', views.download_excel_template, name='download_excel_template'),
    path('user_login/',views.user_login, name="user_login"),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
    path('success/', views.success_page, name='success_page'),
    path('create_student_project/', views.create_student_project, name='create_student_project'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
                    template_name="registration/password_reset.html"
    ),name="reset_password"),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),name="pasword_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),name="password_reset_complete"),
    path('activate/<uidb64>/<token>/',activate, name="activate"),
    path('editor/',views.editor, name="editor"),
    path('enquiry',views.enquiry, name="enquiry"),
    path('message',views.message, name="message"),
    path('advocacy',views.create_advocacy_visit, name="advocacy"),
    
    # URLS for Student
    path('student_home/', StudentViews.student_home, name="student_home"),
    path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_feedback/', StudentViews.student_feedback, name="student_feedback"),
    path('student_feedback_save/', StudentViews.student_feedback_save, name="student_feedback_save"),
    path('student_profile/', StudentViews.student_profile, name="student_profile"),
    path('student_profile_update/', StudentViews.student_profile_update, name="student_profile_update"),
    path('student_view_result/',StudentViews.student_report, name="student_view_result"),
    path('notification/', StudentViews.notifications, name="notification"),
    path('notification_read/<int:id>/', StudentViews.mark_notification_as_read, name="notification_read"),
    path("student_leaderboard/",StudentViews.leaderboard, name="student_leaderboard"),
    path("subjects/",StudentViews.subjects, name="subjects"),
    path('sstudent_login_activity/', StudentViews.student_login_activity, name='sstudent_login_activity'),
    path('sstudent_activity/<str:user_id>/', StudentViews.student_activity_view, name='sstudent_activity'),
    path('projectsample/', StudentViews.SampleProjectReport, name='projectsample'),
    
    # URLS for School
    path('school_home/', SchoolView.school_home, name="school_home"),
    path('attendance_data/', SchoolView.student_data_view, name="attendance_data"),
    path('attendance_data_post/', SchoolView.student_view_data_post, name="attendance_data_post"),
    path('teachers_list/', SchoolView.display_teachers, name="teachers_list"),
    path('subject_list/', SchoolView.subject_list, name="subject_list"),
    path('school_profile/', SchoolView.school_profile, name="school_profile"),
    path('school_profile_update/', SchoolView.school_profile_update, name="school_profile_update"),
    path('school_feedback/', SchoolView.school_feedback, name="school_feedback"),
    path('school_feedback_save/', SchoolView.school_feedback_save, name="school_feedback_save"),
    path('school_notification/', SchoolView.notifications, name="school_notification"),
    path('school_notification_read/<int:id>/', SchoolView.mark_notification_as_read, name="school_notification_read"),
    path("leaderboard/",SchoolView.leaderboard, name="leaderboard"),
    path("student_report", SchoolView.student_report, name="student_report"),
    path('student_report_gradewise/<int:grade>/<str:section>/', SchoolView.student_report_gradewise, name='student_report_gradewise'),
    path("student_detail_report/<user_id>", SchoolView.student_detail_report, name="student_detail_report"),
    path('student_activity/<str:user_id>/', SchoolView.student_activity_view, name='student_activity'),
    path("advocacy_list_school",SchoolView.advocacy, name="advocacy_list_school"),
    path('get_report/<int:id>/', SchoolView.get_report, name='get_report_school'),
    path('school_macroplanners/', SchoolView.view_macroplanner, name='school_macroplanner'),
    path('school_microplanners/', SchoolView.view_microplanner, name='school_microplanner'),
    path('school_timetable/', SchoolView.view_timetable ,name='school_timetable'),
    path('inventory_list/', SchoolView.inventory ,name='inventory'),
    path('kreativityshow/', SchoolView.kreativityshow ,name='kreativityshow'),
    path('guestsession/', SchoolView.guestsession ,name='guestsession'),
    path("tleaderboard_school/",SchoolView.leaderboard, name="tleaderboard_school"),
    path("competition/",SchoolView.competition, name="competition"),
    path("innovation/",SchoolView.innovation, name="innovation"),
    path("student_performance/",SchoolView.StudentPerformance, name="student_performance"),
    path('school_login_activity/', SchoolView.school_login_activity, name='school_login_activity'),
    
    # URLS for principal
    path('principal_home/', PrincipalView.principal_home, name="principal_home"),
    path('attendance_data/', PrincipalView.student_data_view, name="attendance_data"),
    path('attendance_data_post/', PrincipalView.student_view_data_post, name="attendance_data_post"),
    path('pteachers_list/', PrincipalView.display_teachers, name="pteachers_list"),
    path('psubject_list/', PrincipalView.subject_list, name="psubject_list"),
    path('principal_profile/', PrincipalView.school_profile, name="principal_profile"),
    path('principal_profile_update/', PrincipalView.school_profile_update, name="principal_profile_update"),
    path('principal_feedback/', PrincipalView.school_feedback, name="principal_feedback"),
    path('principal_feedback_save/', PrincipalView.school_feedback_save, name="principal_feedback_save"),
    path('principal_notification/', PrincipalView.notifications, name="principal_notification"),
    path('principal_notification_read/<int:id>/', PrincipalView.mark_notification_as_read, name="principal_notification_read"),
    path("pleaderboard/",PrincipalView.leaderboard, name="pleaderboard"),
    path("pstudent_report", PrincipalView.student_report, name="pstudent_report"),
    path("pstudent_report_gradewise/<str:grade>/", PrincipalView.student_report_gradewise, name="pstudent_report_gradewise"),
    path("pstudent_detail_report/<user_id>", PrincipalView.student_detail_report, name="pstudent_detail_report"),
    
     # URLS for teacher
    path('teacher_home/', TeacherView.teacher_home, name="teacher_home"),
    path('tsubject_list/', TeacherView.subject_list, name="tsubject_list"),
    path('teacher_profile/', TeacherView.teacher_profile, name="teacher_profile"),
    path('teacher_profile_update/', TeacherView.teacher_profile_update, name="teacher_profile_update"),
    path('teacher_feedback/', TeacherView.teacher_feedback, name="teacher_feedback"),
    path('teacher_feedback_save/', TeacherView.teacher_feedback_save, name="teacher_feedback_save"),
    path('teacher_notification/', TeacherView.notifications, name="teacher_notification"),
    path('upload-lesson-plan/', TeacherView.upload_lesson_plan, name='lesson_plan_upload'),
    path('upload_micro_plan/', TeacherView.upload_micro_plan, name='upload_micro_plan'),
    path('macroplanners/', TeacherView.view_macroplanner, name='view_macroplanner'),
    path('microplanners/', TeacherView.view_microplanner, name='view_microplanner'),
    path('download-macroplanner-template/', TeacherView.download_macroplanner_template, name='download_macroplanner_template'),
    path('download-microplanner-template/', TeacherView.download_microplanner_template, name='download_microplanner_template'),
    path('get_report1/<int:id>/', TeacherView.get_report, name='get_report1'),
    path('teacher_notification_read/<int:id>/', TeacherView.mark_notification_as_read, name="teacher_notification_read"),
    path("tleaderboard/",TeacherView.leaderboard, name="tleaderboard"),
    path("tstudent_report", TeacherView.student_report, name="tstudent_report"),
    path("tstudent_report_gradewise/<int:grade>/<str:section>/", TeacherView.student_report_gradewise, name="tstudent_report_gradewise"),
    path("tstudent_detail_report/<user_id>", TeacherView.student_detail_report, name="tstudent_detail_report"),
    path('advocacy_list',TeacherView.advocacy_visit, name="advocacy_list"),
    path('timetable',TeacherView.upload_timetable, name="timetable"),
    path('view_timetable',TeacherView.view_timetable, name="view_timetable"),
    path('kreativityshow2/', TeacherView.kreativityshow ,name='kreativityshow2'),
    path('guestsession2/', TeacherView.guestsession ,name='guestsession2'),
    path("competition2/",TeacherView.competition, name="competition2"),

ebook/models.py
from django.db import models
from curriculum.models import *

# Create your models here.
class Ebook(models.Model):
    book_id=models.CharField(max_length=50, default="")
    title = models.CharField(max_length=200)
    slug = models.SlugField(null=True, blank=True)
    author = models.CharField(max_length=100)
    grade = models.ForeignKey(Standard, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Topic_name(models.Model):
    topic_id=models.CharField(max_length=50)
    lesson_name=models.CharField(max_length=50)
    book=models.ForeignKey(Ebook, on_delete=models.CASCADE, related_name='ebook_lessons')
    slug = models.SlugField(null=True, blank=True)
    # pdf = models.FileField(upload_to='ebooks/pdfs/')
    file=models.URLField(verbose_name="content", max_length=300,default="")

    def __str__(self):
        return self.lesson_name

curriculum/forms.py
from django import forms
from .models import Comment, Reply, Lesson

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_id','name','position','video','ppt','Notes')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

ebook/views.py
from django.shortcuts import render, get_object_or_404
from .models import Standard, Ebook, Topic_name

def grade_list(request):
    grades = Standard.objects.all()
    return render(request, 'curriculum/gradelist.html', {'grades': grades})

def ebook_list(request, grade_id):
    grade = get_object_or_404(Standard, id=grade_id)
    ebooks = Ebook.objects.filter(grade=grade)
    return render(request, 'curriculum/ebook.html', {'grade': grade, 'ebooks': ebooks})

def display_lessons(request, book_id):
    book = get_object_or_404(Ebook, id=book_id)
    lessons = Topic_name.objects.filter(book=book)
    return render(request, 'curriculum/e_lesson.html', {'book': book, 'lessons': lessons})

templates/curriculum/a.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}

{% block image_block %}
<header class="info-header4">
  <div id="page-intro" class="container-fluid d-flex align-items-center
    justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold p-5 " style="color:#ff5722;">
          {{subjects.name}} </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'users:index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list'
                slug=subjects.standard.slug %}">{{subjects.standard}}</a></li>
            <li class="disabled-text">{{subjects.name}}</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h6 class="white-text my-4">Robotics, Coding and Artificial Intelligence helps you to understand the theoretical learning in real life applications.</h6>
      </div>
    </header>
    {% endblock %}


    {% block body %}
    <section id="best-features" class="text-center">
      <h2 class="mb-3 mt-5 font-weight-bold" style="color:#ff5722;">Dive Deeper</h2>
      <!-- class row for description-->
      <div class="row d-flex justify-content-center mb-2">
        <!-- class column -->
        <div class="col-md-8 mb-2">
          <p class="dark-text">Robotics, Coding and Artificial Intelligence helps you to understand the theoretical learning in real life applications.</p>
        </div>
      </div>
      <!-- class row2 for cards -->
    <div class="row d-flex justify-content-center mb-3">
        <div class="row d-flex justify-content-evenly">
          {% for lesson in filtered_lessons %}
        {% if lesson.display_on_frontend %}
        <div class="col-md-4">
            <div class="card card-std text-center w-100 my-2">
                <div class="card-header cardgrad1 text-white" style="height:100px;">
                    <div class="row">
                      <div class="col-3" >
                        <i class="fa fa-file-text fa-4x mt-2" aria-hidden="true"></i>
                      </div>
                      <div class="col-9">
                          <h4 class="my-4">Ch-{{lesson.position}}: {{lesson.name}}</h4>
                      </div>
                    </div>
                </div>
                <div class="card-footer">
                  <center>
                      <a href="{% url 'curriculum:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}"> <button type="button" class="btn btncolor" id="btn1"><span class="fw-bolder cardtext1">Get Files</span> &nbsp; <i class="fas fa-arrow-right cardtext1" style="margin-top:5px ;"> </i> </button></a>
                  </center>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        </div>
    </div>
      <div class="row d-flex justify-content-center mb-3">
        {% if user.is_superuser %}
        <a href="{% url 'curriculum:lesson_create'
          standard=subjects.standard.slug slug=subjects.slug %}"><button
            type="button" class="btn btn-success btn-lg btn-bloc"> Add new
            Lesson </button> </a>
        {% endif %}
      </div>

    </section>
  {% endblock %}

templates/curriculum/ebook.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Ablskool - {{ grade.name }}{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row">
        <h2 class="text-center mb-4">Books in Grade: {{ grade.name }}</h2>
        {% for ebook in ebooks %}
            <div class="col-md-3 mb-3 text-center">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ ebook.title }}</h5>
                        <a href="{% url 'ebook:display_lessons' ebook.id %}" class="btn btn-primary">View Lessons</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/curriculum/kits_display.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Ablskool{% endblock %}

{% block body %}
    {% comment %} <div class="container text-center my-5">
        {% for kit in kits %}
        <h3>{{kit.kit_name}}</h3>
            <a href="{% url 'curriculum:models_list' slug=kit.slug%}"> <button type="button" class="btn btncolor" id="btn1"><span class="fw-bolder cardtext1">Get Lessons</span></button></a>
        {% endfor %}
    </div> {% endcomment %}
    <div  class=" container-fluid mt-5 mx-5 my-5">
        <h1 class="text-center my-5  headingtxt">Dive Into Learning</h1>
        <div class="row d-flex justify-content-evenly">
            {% for kit in kits %}
            <div class="col-md-4">
                <div class="card card-std text-center w-75 my-2">
                    <div class="card-header cardgrade text-white ">
                        <div class="row">
                            <div class="col-3" >
                                <!--<i class="fa fa-book-reader fa-4x mt-2"></i>-->
                                <img src="/static/Images/big/mech.png" alt="" style="width:50px;height:50px;">
                            </div>
                            <div class="col-9">
                                <h6 class="display-3 fw-bolder" style="font-size:20px;">{{kit.kit_name}}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <center>
                            <a href="{% url 'mechanzo:models_list' slug=kit.slug%}"> <button type="button" class="btn btncolor" id="btn1"><span class="fw-bolder cardtext1">Let's Get Started</span> &nbsp; <i
                                        class="fas fa-arrow-right cardtext1" style="margin-top:5px ;"> </i> </button> </a> 
                        </center>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
      </div>
{% endblock %}

templates/curriculum/lesson_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Lesson Delete {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Lesson Deletion </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">{{lessons.name}}</a></li>
            <li class="disabled-text" >Lesson Delete</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}



{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Delete {{lessons.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
</section>

<h3 class="mb-4" style="color:#ff5722;">Are you sure you want to delete {{lessons.name}} chapter?</h3>

<form method="post">
  {% csrf_token %}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Delete" class="btn btn-danger btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-warning btn-block">Cancel Deletion</a>
        </div>
  </div>
</form>

{% endblock %}

templates/curriculum/lesson_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Lesson Update {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Lesson Update </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">{{lessons.name}}</a></li>
            <li class="disabled-text" >Lesson Update</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}


{% block body %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Update {{lessons.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
</section>


<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form|crispy}}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Update" class="btn btn-warning btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-danger btn-block">Cancel Update</a>
        </div>
</div>
</form>

{% endblock %}