api/urls.py
from django.urls import path,include
from rest_framework import routers
from api.views import StandardViewSet,SubjectViewSet,LessonViewSet,UserViewSet

router=routers.DefaultRouter()
router.register(r'users',UserViewSet)
router.register(r'standards', StandardViewSet, basename='standard')
router.register(r'subjects', SubjectViewSet,basename='subject')
router.register(r'lessons', LessonViewSet,basename='lesson')

urlpatterns = [
    path('', include(router.urls)),
]

curriculum/urls.py
from django.urls import path,include
from . import views

app_name='curriculum'
urlpatterns = [
    path('training_level/',views.training_level, name="training_level"),
    path('trainer_subject_1/',views.trainer_subject_1, name="trainer_subject_1"),
    path('trainer_subject_2/',views.trainer_subject_2, name="trainer_subject_2"),
    path('trainer_subject_3/',views.trainer_subject_3, name="trainer_subject_3"),
    path('trainer_lesson/<slug:slug>',views.trainer_lesson,name="trainer_lesson"),
    path('mentor/level/', views.mentor_training_level, name='mentor_training_level'),
    path('mentor/subjects/<str:level>/', views.mentor_subjects_by_level, name='mentor_subjects_by_level'),
    path('mentor/lessons/<slug:subject_slug>/<module>/', views.mentor_lesson_by_module, name='mentor_lesson_by_module'),
    path('mentor/lesson/<slug:slug>/', views.mentor_lesson_detail, name='mentor_lesson_detail'),
    path('rate-lecture/', views.LectureRatingCreateView.as_view(), name='rate-lecture'),
    path("trainer_lesson_detail/<slug:slug>",views.trainer_lesson_detail, name="trainer_lesson_detail"),
    path('coding/', views.coding, name="coding"),
    path('codinglessons/<slug:slug>/',views.codinglessons,name="codinglessons"),
    path('codinglesson_detail/<slug:slug>/',views.codinglesson_detail, name="codinglesson_detail"),
    path('ai/',views.ai,name="ai"),
    path('lessons/<slug:slug>/',views.lessons,name="lessons"),
    path('lesson_detail/<slug:slug>/',views.lesson_detail, name="lesson_detail"),
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),
    # path("mechanzo_kits/", views.display_kits, name="mechanzo_kits"),
    # path("<slug:slug>/", views.display_models, name="models_list")
]

ebook/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('grades/', views.grade_list, name='grade_list'),
    path('grades/<int:grade_id>/books/', views.ebook_list, name='ebook_list'),
    path('books/<int:book_id>/lessons/', views.display_lessons, name='display_lessons'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('curriculum/', include(('curriculum.urls','curriculum'), namespace='curriculum')),
    path('mechanzo/', include(('mechanzo.urls','mechanzo'),namespace="mechanzo")),
    # path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('ebook/', include(('ebook.urls', 'ebook'), namespace='ebook')),
    path('', include('pwa.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

mechanzo/urls.py
from django.urls import path,include
from . import views

app_name='mechanzo'
urlpatterns = [
    path("", views.display_kits, name="mechanzo_kits"),
    path("<slug:slug>/", views.display_models, name="models_list")
]

users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from users.utils import activate
from . import StudentViews
from . import SchoolView,PrincipalView,TeacherView

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('student/', views.StudentSignUpView.as_view(), name="user_student"),
    path('parent/', views.ParentSignUpView.as_view(), name="user_parent"),
    path('teacher/', views.TeacherSignUpView.as_view(), name="user_teacher"),
    path('principal/', views.PrincipalSignUpView.as_view(), name="user_principal"),
    path('school/', views.SchoolSignUpView.as_view(), name="user_school"),
    path('students_registration/',views.register_student_from_excel, name="students_registration"),
    path('download-excel-template/', views.download_excel_template, name='download_excel_template'),
    path('user_login/',views.user_login, name="user_login"),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
    path('success/', views.success_page, name='success_page'),
    path('create_student_project/', views.create_student_project, name='create_student_project'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
                    template_name="registration/password_reset.html"
    ),name="reset_password"),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),name="pasword_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),name="password_reset_complete"),
    path('activate/<uidb64>/<token>/',activate, name="activate"),
    path('editor/',views.editor, name="editor"),
    path('enquiry',views.enquiry, name="enquiry"),
    path('message',views.message, name="message"),
    path('advocacy',views.create_advocacy_visit, name="advocacy"),
    
    # URLS for Student
    path('student_home/', StudentViews.student_home, name="student_home"),
    path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_feedback/', StudentViews.student_feedback, name="student_feedback"),
    path('student_feedback_save/', StudentViews.student_feedback_save, name="student_feedback_save"),
    path('student_profile/', StudentViews.student_profile, name="student_profile"),
    path('student_profile_update/', StudentViews.student_profile_update, name="student_profile_update"),
    path('student_view_result/',StudentViews.student_report, name="student_view_result"),
    path('notification/', StudentViews.notifications, name="notification"),
    path('notification_read/<int:id>/', StudentViews.mark_notification_as_read, name="notification_read"),
    path("student_leaderboard/",StudentViews.leaderboard, name="student_leaderboard"),
    path("subjects/",StudentViews.subjects, name="subjects"),
    path('sstudent_login_activity/', StudentViews.student_login_activity, name='sstudent_login_activity'),
    path('sstudent_activity/<str:user_id>/', StudentViews.student_activity_view, name='sstudent_activity'),
    path('projectsample/', StudentViews.SampleProjectReport, name='projectsample'),
    
    # URLS for School
    path('school_home/', SchoolView.school_home, name="school_home"),
    path('attendance_data/', SchoolView.student_data_view, name="attendance_data"),
    path('attendance_data_post/', SchoolView.student_view_data_post, name="attendance_data_post"),
    path('teachers_list/', SchoolView.display_teachers, name="teachers_list"),
    path('subject_list/', SchoolView.subject_list, name="subject_list"),
    path('school_profile/', SchoolView.school_profile, name="school_profile"),
    path('school_profile_update/', SchoolView.school_profile_update, name="school_profile_update"),
    path('school_feedback/', SchoolView.school_feedback, name="school_feedback"),
    path('school_feedback_save/', SchoolView.school_feedback_save, name="school_feedback_save"),
    path('school_notification/', SchoolView.notifications, name="school_notification"),
    path('school_notification_read/<int:id>/', SchoolView.mark_notification_as_read, name="school_notification_read"),
    path("leaderboard/",SchoolView.leaderboard, name="leaderboard"),
    path("student_report", SchoolView.student_report, name="student_report"),
    path('student_report_gradewise/<int:grade>/<str:section>/', SchoolView.student_report_gradewise, name='student_report_gradewise'),
    path("student_detail_report/<user_id>", SchoolView.student_detail_report, name="student_detail_report"),
    path('student_activity/<str:user_id>/', SchoolView.student_activity_view, name='student_activity'),
    path("advocacy_list_school",SchoolView.advocacy, name="advocacy_list_school"),
    path('get_report/<int:id>/', SchoolView.get_report, name='get_report_school'),
    path('school_macroplanners/', SchoolView.view_macroplanner, name='school_macroplanner'),
    path('school_microplanners/', SchoolView.view_microplanner, name='school_microplanner'),
    path('school_timetable/', SchoolView.view_timetable ,name='school_timetable'),
    path('inventory_list/', SchoolView.inventory ,name='inventory'),
    path('kreativityshow/', SchoolView.kreativityshow ,name='kreativityshow'),
    path('guestsession/', SchoolView.guestsession ,name='guestsession'),
    path("tleaderboard_school/",SchoolView.leaderboard, name="tleaderboard_school"),
    path("competition/",SchoolView.competition, name="competition"),
    path("innovation/",SchoolView.innovation, name="innovation"),
    path("student_performance/",SchoolView.StudentPerformance, name="student_performance"),
    path('school_login_activity/', SchoolView.school_login_activity, name='school_login_activity'),
    
    # URLS for principal
    path('principal_home/', PrincipalView.principal_home, name="principal_home"),
    path('attendance_data/', PrincipalView.student_data_view, name="attendance_data"),
    path('attendance_data_post/', PrincipalView.student_view_data_post, name="attendance_data_post"),
    path('pteachers_list/', PrincipalView.display_teachers, name="pteachers_list"),
    path('psubject_list/', PrincipalView.subject_list, name="psubject_list"),
    path('principal_profile/', PrincipalView.school_profile, name="principal_profile"),
    path('principal_profile_update/', PrincipalView.school_profile_update, name="principal_profile_update"),
    path('principal_feedback/', PrincipalView.school_feedback, name="principal_feedback"),
    path('principal_feedback_save/', PrincipalView.school_feedback_save, name="principal_feedback_save"),
    path('principal_notification/', PrincipalView.notifications, name="principal_notification"),
    path('principal_notification_read/<int:id>/', PrincipalView.mark_notification_as_read, name="principal_notification_read"),
    path("pleaderboard/",PrincipalView.leaderboard, name="pleaderboard"),
    path("pstudent_report", PrincipalView.student_report, name="pstudent_report"),
    path("pstudent_report_gradewise/<str:grade>/", PrincipalView.student_report_gradewise, name="pstudent_report_gradewise"),
    path("pstudent_detail_report/<user_id>", PrincipalView.student_detail_report, name="pstudent_detail_report"),
    
     # URLS for teacher
    path('teacher_home/', TeacherView.teacher_home, name="teacher_home"),
    path('tsubject_list/', TeacherView.subject_list, name="tsubject_list"),
    path('teacher_profile/', TeacherView.teacher_profile, name="teacher_profile"),
    path('teacher_profile_update/', TeacherView.teacher_profile_update, name="teacher_profile_update"),
    path('teacher_feedback/', TeacherView.teacher_feedback, name="teacher_feedback"),
    path('teacher_feedback_save/', TeacherView.teacher_feedback_save, name="teacher_feedback_save"),
    path('teacher_notification/', TeacherView.notifications, name="teacher_notification"),
    path('upload-lesson-plan/', TeacherView.upload_lesson_plan, name='lesson_plan_upload'),
    path('upload_micro_plan/', TeacherView.upload_micro_plan, name='upload_micro_plan'),
    path('macroplanners/', TeacherView.view_macroplanner, name='view_macroplanner'),
    path('microplanners/', TeacherView.view_microplanner, name='view_microplanner'),
    path('download-macroplanner-template/', TeacherView.download_macroplanner_template, name='download_macroplanner_template'),
    path('download-microplanner-template/', TeacherView.download_microplanner_template, name='download_microplanner_template'),
    path('get_report1/<int:id>/', TeacherView.get_report, name='get_report1'),
    path('teacher_notification_read/<int:id>/', TeacherView.mark_notification_as_read, name="teacher_notification_read"),
    path("tleaderboard/",TeacherView.leaderboard, name="tleaderboard"),
    path("tstudent_report", TeacherView.student_report, name="tstudent_report"),
    path("tstudent_report_gradewise/<int:grade>/<str:section>/", TeacherView.student_report_gradewise, name="tstudent_report_gradewise"),
    path("tstudent_detail_report/<user_id>", TeacherView.student_detail_report, name="tstudent_detail_report"),
    path('advocacy_list',TeacherView.advocacy_visit, name="advocacy_list"),
    path('timetable',TeacherView.upload_timetable, name="timetable"),
    path('view_timetable',TeacherView.view_timetable, name="view_timetable"),
    path('kreativityshow2/', TeacherView.kreativityshow ,name='kreativityshow2'),
    path('guestsession2/', TeacherView.guestsession ,name='guestsession2'),
    path("competition2/",TeacherView.competition, name="competition2"),

templates/users/advocay.html
{% extends "base.html" %}

{% block body %}
<section id="advocacy">
<div class="container">
    <h2>Advocacy Form</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
</section>

{% endblock %}

templates/users/contact.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Contact Us{% endblock %}
{% block body %}
<section id="contact-body">
    <div class="contact-form">
        <img alt="" class="avatar" src="/static/Images/user_avatar.png">
        <h2>Contact Us</h2>
        <form action="{% url 'users:contact' %}" method="post">
        {% csrf_token %}
            <p>Name</p><input placeholder="Enter your name" id="name" name="name" type="text">
            <p>Contact number</p><input placeholder="Enter your contact number" id="contact" name="contact" type="tel">
            <p>Email</p><input placeholder="Enter your email" id="email" type="email" name="email">
            <p>Your Message</p><input placeholder="Leave your message" id="message" type="text" name="message">
            <input type="submit" value="Submit">
        </form>
    </div>
</section>
{% endblock %}

templates/users/demo_success.html
<!DOCTYPE html>
<html>
<head>
    <title>Project Submission Successful</title>
</head>
<body>
    <h1>Project Submission Successful</h1>
    <p>You have successfully submitted your project. We will get in touch with you shortly.</p>
</body>
</html>

templates/users/email_verification.html
Someone asked for password email verification {{ user.email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url "users:activate" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

templates/users/footer.html
{% load static %}

<section id="footer">
    <div class="footer-dark bg-footer">
            <div class="container" style="min-height:35vh;">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3 class="mx-3">LMS</h3>
                        <ul>
                            <li><a href="/">Home</a></li>
                            <li><a href="https://ablskool.com/curriculum/">Courses</a></li>
                            <li><a href="https://drive.google.com/file/d/1Czd7cDmayl4Q2jlO6nzcVuFrlX59wcB-/view?usp=sharing" target="_blank">STEM Progressive Curriculum</a></li>
                            <li><a href="https://drive.google.com/file/d/1mfH8TRP6k49n_v7ndb2oStwwb6wSZcv4/view?usp=sharing" target="_blank">ROFL Progressive Curriculum</a></li>
                            <li><a href="{% url 'mechanzo:mechanzo_kits' %}">Mechanzo</a></li>
                            <li><a href="{% url 'users:create_student_project' %}">Innovative Project</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3 class="mx-3">About</h3>
                        <ul>
                            <li><a href="https://ableducation.com/">ABL Education</a></li>
                            <li><a href="https://ablkart.com/">ABL kart</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="https://ableducation.com/career.php">Career</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <div class="footer-top-menu">
                            <h3 class="widget-title mx-3">School Program</h3>
                            <div class="fo-course-container">
                                <ul>
                                    <li><a href="https://ableducation.com/stem-lab.php" target="_blank">STEM Program</a></li>
                                    <li><a href="https://ableducation.com/scienceprogram.php" target="_blank">Science Program</a></li>
                                    <li><a href="https://ableducation.com/atl.php" target="_blank">Atal Tinkering Lab</a></li>
                                    <li><a href="https://ableducation.com/robotics_lab.php" target="_blank">Robotics Lab</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-3 item">
                        <h3 class="mx-3">DIY Tinkering Kit</h3>
                        <ul>
                            <li><a href="https://ablkart.com/sub-category/mechanzo-kits" target="_blank">Robotics Kit</a></li>
                            <li><a href="https://ablkart.com/sub-category/electronics-kits" target="_blank">Tinkering Kits</a></li>
                            <li><a href="https://ablkart.com/category/science-activities" target="_blank">Science Activities</a></li>
                            <li><a href="https://ablkart.com/category/tinker-with-arduino" target="_blank">Arduino</a></li>
                            <li><a href="https://ablkart.com/sub-category/raspberry-pi-kits" target="_blank">Raspberry Pi</a></li> 
                            <li><a href="https://ablkart.com/category/iot-kits" target="_blank">IoT</a></li> 
                            <li><a href="https://ablkart.com/sub-category/arduino-add-ons" target="_blank">Modules and Accessories</a></li> 
                        </ul>
                    </div>

                    <div class="col-sm-6 col-md-3 item">
                        <h3 class="mx-3">Kreativity League</h3>
                        <ul>
                            <li><a href="https://kreativityleague.com/" target="_blank">Gallery</a></li>
                        </ul>
                    </div>

                    <div class="col-sm-6 col-md-3 item">
                        <div class="footer-top-menu">
                            <h3 class="widget-title mx-3">Contact Us</h3>
                            <div class="fo-course-container">
                                <ul>
                                    <li>
                                        <button class="open-button btn btn-light" onclick="openForm()" style="margin-left:15px;">Enquire</button>
                                        <div class="form-popup" id="myForm">
                                        <form action="{% url 'users:enquiry' %}" class="form-container" method="post">
                                            {% csrf_token %}
                                            {% comment %} <label for="name"><b>Name</b></label> {% endcomment %}
                                            <input type="text" placeholder="Name" name="name" id="form_content" required>
            
                                            {% comment %} <label for="contact"><b>Contact</b></label> {% endcomment %}
                                            <input type="text" placeholder="Contact" name="contact" required>
            
                                            {% comment %} <label for="email"><b>Email</b></label> {% endcomment %}
                                            <input type="email" placeholder="Email" name="email" required>
            
                                            {% comment %} <label for="query"><b>Query</b></label> {% endcomment %}
                                            <input type="text" placeholder="Query" name="query" required>
                                            <button type="submit" class="btn" id="enquiry-button">Submit</button>
                                            <button type="button" class="btn cancel" onclick="closeForm()" id="enquiry-button">Close</button>
                                        </form>
                                        </div>
                                    </li>
                                    {% comment %} <li><a href="{% url 'users:book_demo'%}"><button id="bookDemoButton" class="btn btn-light" style="margin-bottom:20px; margin-top:5px;">Book a Demo</button></a></li> {% endcomment %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    
                    {% if request.user.email in allowed_emails %}
                    <div class="col-sm-6 col-md-3 item">
                        <h3 class="mx-3">Advocacy</h3>
                        <ul>
                            <li><a href="{% url 'users:advocacy' %}">Advocacy Form</a></li>
                        </ul>
                    </div>
                    {% endif %}

                </div>
            </div>
    </div>
</section>

templates/users/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Login Form{% endblock %}
{% block body %}
<section id="login">
    <div class="login-form">
        <img alt="" class="avatar" src="/static/Images/user_avatar.png">
        <h2>Login</h2>
        <form action="{% url 'users:user_login' %}" method="post">
        {% csrf_token %}
            <!--<p>Email</p><input name="email" placeholder="Enter your mail id" type="text">-->
            <input type="text" name="username" placeholder="Username or Email">
            <p>Password</p><input name="password" placeholder="Enter your password" type="password">
            <div class="input-group">
                <div class="g-recaptcha" data-sitekey="6LeLgcEkAAAAAMu2Y7-64FZFdZZ6693CmBljwEEA"></div>
            </div>
            <input type="submit" value="Login">
            <button class="btn" >
                <a id="google" class="text-white" href="">
                    Login with Google
                </a>
            </button>
            <h6 class="text-center"><a class="text-white" href="{% url 'users:reset_password' %}">Reset Password?</a></h6>
            <div class="mb-4 text-center">
                <p>Don't have an account yet ? <a class="text-white" href="{% url 'users:register' %}"> Register Here</a></p>
                <!--<h6><a class="text-white" href="{% url 'users:register' %}">Register Here</a></h6>-->
            </div>
        </form>
    </div>
</section>
{% endblock %}

templates/users/navbar.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark ">
        <div class="container-fluid">
          <a class="navbar-brand rounded-circle pb-2" href="/"><img src="/static/Images/skool.png"
              alt="ABL Education"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mx-2 mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/" style="font-size:20px;"><i class="fa fa-home fa-fw" aria-hidden="true"></i></a>
              </li>
              <li class="nav-item dropdown mx-2" >
                <a class="nav-link active dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size:20px;" >
                  Courses
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
                  <li><a class="dropdown-item" href="{% url 'curriculum:standard_list' %}" style="font-size:20px;">STEM</a></li>
                  <li><hr class="dropdown-divider" ></li>
                  <li><a class="dropdown-item" href="{% url 'curriculum:coding'%}" style="font-size:20px;">Coding</a></li>
                  <li><a class="dropdown-item" href="{% url 'curriculum:ai'%}" style="font-size:20px;">Artificial Intelligence</a>
                  </li>
                  {% if user.email == 'teachers.training@thinnkware.com' %}
                  <li><a class="dropdown-item" href="{% url 'curriculum:training_level'%}" style="font-size:20px;">Training Module</a></li>
                  {% endif %}
                </ul>
              </li>
              <li class="nav-item dropdown mx-4" >
                <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size:20px;" >
                  Explore
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
                  <li><a class="dropdown-item" href="http://ableducation.com/" target="_blank" style="font-size:20px;">ABL Education</a></li>
                  <li><a class="dropdown-item" href="https://ablkart.com/" target="_blank" style="font-size:20px;">ABL Kart</a></li>
                  <li><a class="dropdown-item" href="https://kreativityleague.com/" target="_blank" style="font-size:20px;">Kreativity League</a></li>
                </ul>
              </li>
              {% if user.is_superuser %}
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'admin:index'%}" style="font-size:20px;"><i class="fa fa-unlock"></i></span> </a>
              </li>
              {% endif %}
              {% if user.is_superuser %}
              <li class="nav-item ">
                <a class="nav-link active" href="{% url 'ebook:grade_list'%}" style="font-size:20px;">E-book</a>
              </li>
              {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto" id="auth">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown" role="button">
                    <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size:20px;" >
                  {{user.username}}
                    </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
                    {% if user.is_student %}
                  <li><a class="dropdown-item" href="{% url 'users:student_home' %}" style="font-size:20px;">My dashboard</a></li>
                  {% elif user.is_school %}
                  <li><a class="dropdown-item" href="{% url 'users:school_home' %}" style="font-size:20px;">School dashboard</a></li>
                  {% elif user.is_principal %}
                  <li><a class="dropdown-item" href="{% url 'users:principal_home' %}" style="font-size:20px;">My dashboard</a></li>
                  {% elif user.is_teacher %}
                  <li><a class="dropdown-item" href="{% url 'users:teacher_home' %}" style="font-size:20px;">My dashboard</a></li>
                    {% endif %}
                  <li><a class="dropdown-item" href="/logout" style="font-size:20px;">Logout</a></li>
                </ul>
              </li>
              {% else %}
              <li class="nav-item ">
                <a class="nav-link active" href="{% url 'users:user_login' %}" style="font-size:20px;"><i class="fa fa-sign-in mx-2" ></i>Login</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link active" href="/register" style="font-size:20px;"><i class="fa fa-regular fa-pencil mx-2"></i>Register</span> </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>
</body>
</html>

templates/users/parent.html
{% extends 'base.html' %}

{% load static %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}
{% block title %}Parent Form{% endblock %}
{% block body %}
<section id="parent-body">
    <div class="parent-form">
        <img alt="" class="avatar" src="/static/Images/user_avatar.png">
        <h2>Registration Form</h2>
        <form action="{% url 'users:user_parent' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
            <input type="submit" value="Submit">
        </form>
    </div>
</body>
{% endblock %}

templates/users/registration_with_excel.html
{% extends 'base.html' %}

{% block title %}Student Form{% endblock %}

{% block body %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Upload Student Excel File</h5>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" action="{% url 'users:students_registration' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="excel_file">Select Excel File:</label>
                            <input type="file" name="excel_file" id="excel_file" class="form-control-file">
                        </div>
                        <button type="submit" class="btn btn-primary">Upload</button>
                    </form>
                </div>
                <div class="card-footer">
                    <p>Download Excel template:</p>
                    <a href="{% url 'users:download_excel_template' %}" class="btn btn-secondary">Download Template</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}