api/urls.py
from django.urls import path,include
from rest_framework import routers
from api.views import StandardViewSet,SubjectViewSet,LessonViewSet,UserViewSet

router=routers.DefaultRouter()
router.register(r'users',UserViewSet)
router.register(r'standards', StandardViewSet, basename='standard')
router.register(r'subjects', SubjectViewSet,basename='subject')
router.register(r'lessons', LessonViewSet,basename='lesson')

urlpatterns = [
    path('', include(router.urls)),
]

lms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('curriculum/', include(('curriculum.urls','curriculum'), namespace='curriculum')),
    path('mechanzo/', include(('mechanzo.urls','mechanzo'),namespace="mechanzo")),
    # path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('ebook/', include(('ebook.urls', 'ebook'), namespace='ebook')),
    path('', include('pwa.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from users.utils import activate
from . import StudentViews
from . import SchoolView,PrincipalView,TeacherView

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('student/', views.StudentSignUpView.as_view(), name="user_student"),
    path('parent/', views.ParentSignUpView.as_view(), name="user_parent"),
    path('teacher/', views.TeacherSignUpView.as_view(), name="user_teacher"),
    path('principal/', views.PrincipalSignUpView.as_view(), name="user_principal"),
    path('school/', views.SchoolSignUpView.as_view(), name="user_school"),
    path('students_registration/',views.register_student_from_excel, name="students_registration"),
    path('download-excel-template/', views.download_excel_template, name='download_excel_template'),
    path('user_login/',views.user_login, name="user_login"),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
    path('success/', views.success_page, name='success_page'),
    path('create_student_project/', views.create_student_project, name='create_student_project'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
                    template_name="registration/password_reset.html"
    ),name="reset_password"),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),name="pasword_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),name="password_reset_complete"),
    path('activate/<uidb64>/<token>/',activate, name="activate"),
    path('editor/',views.editor, name="editor"),
    path('enquiry',views.enquiry, name="enquiry"),
    path('message',views.message, name="message"),
    path('advocacy',views.create_advocacy_visit, name="advocacy"),
    
    # URLS for Student
    path('student_home/', StudentViews.student_home, name="student_home"),
    path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_feedback/', StudentViews.student_feedback, name="student_feedback"),
    path('student_feedback_save/', StudentViews.student_feedback_save, name="student_feedback_save"),
    path('student_profile/', StudentViews.student_profile, name="student_profile"),
    path('student_profile_update/', StudentViews.student_profile_update, name="student_profile_update"),
    path('student_view_result/',StudentViews.student_report, name="student_view_result"),
    path('notification/', StudentViews.notifications, name="notification"),
    path('notification_read/<int:id>/', StudentViews.mark_notification_as_read, name="notification_read"),
    path("student_leaderboard/",StudentViews.leaderboard, name="student_leaderboard"),
    path("subjects/",StudentViews.subjects, name="subjects"),
    path('sstudent_login_activity/', StudentViews.student_login_activity, name='sstudent_login_activity'),
    path('sstudent_activity/<str:user_id>/', StudentViews.student_activity_view, name='sstudent_activity'),
    path('projectsample/', StudentViews.SampleProjectReport, name='projectsample'),
    
    # URLS for School
    path('school_home/', SchoolView.school_home, name="school_home"),
    path('attendance_data/', SchoolView.student_data_view, name="attendance_data"),
    path('attendance_data_post/', SchoolView.student_view_data_post, name="attendance_data_post"),
    path('teachers_list/', SchoolView.display_teachers, name="teachers_list"),
    path('subject_list/', SchoolView.subject_list, name="subject_list"),
    path('school_profile/', SchoolView.school_profile, name="school_profile"),
    path('school_profile_update/', SchoolView.school_profile_update, name="school_profile_update"),
    path('school_feedback/', SchoolView.school_feedback, name="school_feedback"),
    path('school_feedback_save/', SchoolView.school_feedback_save, name="school_feedback_save"),
    path('school_notification/', SchoolView.notifications, name="school_notification"),
    path('school_notification_read/<int:id>/', SchoolView.mark_notification_as_read, name="school_notification_read"),
    path("leaderboard/",SchoolView.leaderboard, name="leaderboard"),
    path("student_report", SchoolView.student_report, name="student_report"),
    path('student_report_gradewise/<int:grade>/<str:section>/', SchoolView.student_report_gradewise, name='student_report_gradewise'),
    path("student_detail_report/<user_id>", SchoolView.student_detail_report, name="student_detail_report"),
    path('student_activity/<str:user_id>/', SchoolView.student_activity_view, name='student_activity'),
    path("advocacy_list_school",SchoolView.advocacy, name="advocacy_list_school"),
    path('get_report/<int:id>/', SchoolView.get_report, name='get_report_school'),
    path('school_macroplanners/', SchoolView.view_macroplanner, name='school_macroplanner'),
    path('school_microplanners/', SchoolView.view_microplanner, name='school_microplanner'),
    path('school_timetable/', SchoolView.view_timetable ,name='school_timetable'),
    path('inventory_list/', SchoolView.inventory ,name='inventory'),
    path('kreativityshow/', SchoolView.kreativityshow ,name='kreativityshow'),
    path('guestsession/', SchoolView.guestsession ,name='guestsession'),
    path("tleaderboard_school/",SchoolView.leaderboard, name="tleaderboard_school"),
    path("competition/",SchoolView.competition, name="competition"),
    path("innovation/",SchoolView.innovation, name="innovation"),
    path("student_performance/",SchoolView.StudentPerformance, name="student_performance"),
    path('school_login_activity/', SchoolView.school_login_activity, name='school_login_activity'),
    
    # URLS for principal
    path('principal_home/', PrincipalView.principal_home, name="principal_home"),
    path('attendance_data/', PrincipalView.student_data_view, name="attendance_data"),
    path('attendance_data_post/', PrincipalView.student_view_data_post, name="attendance_data_post"),
    path('pteachers_list/', PrincipalView.display_teachers, name="pteachers_list"),
    path('psubject_list/', PrincipalView.subject_list, name="psubject_list"),
    path('principal_profile/', PrincipalView.school_profile, name="principal_profile"),
    path('principal_profile_update/', PrincipalView.school_profile_update, name="principal_profile_update"),
    path('principal_feedback/', PrincipalView.school_feedback, name="principal_feedback"),
    path('principal_feedback_save/', PrincipalView.school_feedback_save, name="principal_feedback_save"),
    path('principal_notification/', PrincipalView.notifications, name="principal_notification"),
    path('principal_notification_read/<int:id>/', PrincipalView.mark_notification_as_read, name="principal_notification_read"),
    path("pleaderboard/",PrincipalView.leaderboard, name="pleaderboard"),
    path("pstudent_report", PrincipalView.student_report, name="pstudent_report"),
    path("pstudent_report_gradewise/<str:grade>/", PrincipalView.student_report_gradewise, name="pstudent_report_gradewise"),
    path("pstudent_detail_report/<user_id>", PrincipalView.student_detail_report, name="pstudent_detail_report"),
    
     # URLS for teacher
    path('teacher_home/', TeacherView.teacher_home, name="teacher_home"),
    path('tsubject_list/', TeacherView.subject_list, name="tsubject_list"),
    path('teacher_profile/', TeacherView.teacher_profile, name="teacher_profile"),
    path('teacher_profile_update/', TeacherView.teacher_profile_update, name="teacher_profile_update"),
    path('teacher_feedback/', TeacherView.teacher_feedback, name="teacher_feedback"),
    path('teacher_feedback_save/', TeacherView.teacher_feedback_save, name="teacher_feedback_save"),
    path('teacher_notification/', TeacherView.notifications, name="teacher_notification"),
    path('upload-lesson-plan/', TeacherView.upload_lesson_plan, name='lesson_plan_upload'),
    path('upload_micro_plan/', TeacherView.upload_micro_plan, name='upload_micro_plan'),
    path('macroplanners/', TeacherView.view_macroplanner, name='view_macroplanner'),
    path('microplanners/', TeacherView.view_microplanner, name='view_microplanner'),
    path('download-macroplanner-template/', TeacherView.download_macroplanner_template, name='download_macroplanner_template'),
    path('download-microplanner-template/', TeacherView.download_microplanner_template, name='download_microplanner_template'),
    path('get_report1/<int:id>/', TeacherView.get_report, name='get_report1'),
    path('teacher_notification_read/<int:id>/', TeacherView.mark_notification_as_read, name="teacher_notification_read"),
    path("tleaderboard/",TeacherView.leaderboard, name="tleaderboard"),
    path("tstudent_report", TeacherView.student_report, name="tstudent_report"),
    path("tstudent_report_gradewise/<int:grade>/<str:section>/", TeacherView.student_report_gradewise, name="tstudent_report_gradewise"),
    path("tstudent_detail_report/<user_id>", TeacherView.student_detail_report, name="tstudent_detail_report"),
    path('advocacy_list',TeacherView.advocacy_visit, name="advocacy_list"),
    path('timetable',TeacherView.upload_timetable, name="timetable"),
    path('view_timetable',TeacherView.view_timetable, name="view_timetable"),
    path('kreativityshow2/', TeacherView.kreativityshow ,name='kreativityshow2'),
    path('guestsession2/', TeacherView.guestsession ,name='guestsession2'),
    path("competition2/",TeacherView.competition, name="competition2"),

templates/principal_template/base_template.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ABL Skool- LMS for students to Learn STEM at their own pace</title>
  <link rel="shortcut icon" type="image/x-icon" href="/static/Images/log.png">
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static "jqvmap/jqvmap.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'  %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "overlayScrollbars/css/OverlayScrollbars.min.css" %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "daterangepicker/daterangepicker.css" %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static "summernote/summernote-bs4.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    {% comment %} For Custom CSS {% endcomment %}

    {% block custom_css %}
    {% endblock custom_css %}

</head>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

  <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>
      <h4 style="margin-left: 10px; margin-top: 5px;">School Dashboard</h4>
      <ul class="navbar-nav mx-4">
        <li class="nav-item">
          <a href="{% url 'users:principal_notification' %}">
            <input type="image" src="/static/Images/users/notification.png" alt="" style="height:20px; width:20px;">
          </a>
        </li>
      </ul>
      <ul class="navbar-nav " style="margin-left:600px;">
        <li class="nav-item"><a href="{% url 'users:index' %}"><i class="fa fa-home fa-fw" aria-hidden="true"></i></a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
            <i class="fas fa-cog"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">
            
            <a href="{% url 'users:principal_profile' %}" class="dropdown-item">
              <i class="fas fa-user-edit mr-2"></i> Update Profile
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'users:user_logout' %}" class="dropdown-item">
              <i class="fas fa-power-off mr-2"></i> Logout
            </a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
     </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    {% include 'principal_template/sidebar_template.html' with user=user id=id %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">
                {% block page_title %}
                {% endblock page_title %}
              </h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href=""></a></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      {% block main_content %}
      {% endblock main_content %}
      <!-- /.content -->
    </div>

    
  </div>
  <!-- ./wrapper -->


<!-- jQuery -->
<script src="{% static "jquery/jquery.min.js"  %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "jquery-ui/jquery-ui.min.js"  %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js"  %}"></script>
<!-- ChartJS -->
<script src="{% static "chart.js/Chart.min.js"  %}"></script>
<!-- Sparkline -->
<script src="{% static "sparklines/sparkline.js"  %}"></script>
<!-- JQVMap -->
<script src="{% static "jqvmap/jquery.vmap.min.js"  %}"></script>
<script src="{% static "jqvmap/maps/jquery.vmap.usa.js"  %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "jquery-knob/jquery.knob.min.js"  %}"></script>
<!-- daterangepicker -->
<script src="{% static "moment/moment.min.js"  %}"></script>
<script src="{% static "daterangepicker/daterangepicker.js"  %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"  %}"></script>
<!-- Summernote -->
<script src="{% static "summernote/summernote-bs4.min.js"  %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "overlayScrollbars/js/jquery.overlayScrollbars.min.js"  %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'  %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js'  %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js'  %}"></script>

{% comment %} For Custom JS {% endcomment %}
{% block custom_js %}
{% endblock custom_js %}

</body>
</html>

templates/principal_template/details_mark.html
{% extends 'principal_template/base_template.html' %}

{% load static %}

{% block page_title %}
    View Result
{% endblock page_title %}

{% block main_content %}
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Subject</th>
                <th>Topic</th>
                <th>Marks</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for mark in marks %}
                <tr>
                    <td>{{mark.quiz.name}}</td>
                    <td>{{mark.quiz.topic}}</td>
                    <td>{{mark.score|floatformat:2}}</td>
                    <td>{% if mark.score >= 80 %}
                        <span class="alert alert-success">Pass</span>
                    {% else %}
                        <span class="alert alert-danger">Fail</span>
                    {% endif %}</td>
                </tr> 
            {% endfor %}
        </tbody>
    </table>
{% endblock main_content %}

templates/principal_template/notification.html
{% extends 'principal_template/base_template.html' %}
{% block page_title %}
Notification
{% endblock page_title %}
{% block main_content %}
    {% for notification in notifications %}
    {% if not notification.read %}
        <ul>
            <li><a href="{% url 'users:school_notification_read' notification.id %}">{{ notification.message }}</a></li>
        </ul>
    {% endif %}
    {% endfor %}
{% endblock main_content %}

templates/principal_template/school_feedback.html
{% extends 'principal_template/base_template.html' %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Chatbox</h3>
                    </div>
                    <!-- /.card-header -->
                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}      
                    <form method="POST" action="{% url 'users:principal_feedback_save' %}">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="form-group">
                                {% comment %} <label>Feedback Message </label> {% endcomment %}
                                <textarea name="feedback_message" class="form-control" rows="6" placeholder="Feedback Message"></textarea>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit Message</button>
                        </div>
                    </form>

                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">Feedback History</h3>
                        </div>
                        <div class="card-body">
                           <div class="table-responsive">
                                <table class="table">
                                    <thead class="thead-light">
                                    <tr>
                                        <th>#ID</th>
                                        <th>Feedback Message</th>
                                        <th>Feedback Reply</th>
                                    </tr>
                                    </thead>  
                                    {% for row in feedback_data %}
                                    <tr>
                                        <td>{{ row.id }}</td>
                                        <td>{{ row.feedback }}</td>
                                        <td>{{ row.feedback_reply }}</td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
      </section>
  {% endblock main_content %}
{% block custom_js %}
{% endblock custom_js %}

templates/principal_template/school_home_template.html
{% extends 'principal_template/base_template.html' %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{ total_student }}</h3>
                        <p>Total Students</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{% url 'users:pstudent_report' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{ teachers }}</h3>
                        <p>Total Teachers</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{% url 'users:pteachers_list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                    <div class="inner">
                        <h3>11</h3>
                        <p>Subjects</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{% url 'users:psubject_list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                    <div class="inner">
                        {% comment %} <h3>{{ total_subjects }}</h3> {% endcomment %}
                        {% if unread_notifications %}  
                            <h3>{{ unread_notifications }}</h3>
                        {% else %}
                            <h3>None</h3>
                        {% endif %}
                        <p>Notification</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="{% url 'users:principal_notification' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

  {% block custom_js %}
    
  {% endblock custom_js %}

templates/principal_template/sidebar_template.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <!--<div class="image">-->
          <!--  {% if school.profile_pic %}-->
          <!--  <img src="{{school.profile_pic.url}}" class="img-circle elevation-2" alt="User Image">-->
          <!--  {% else %}-->
          <!--  <p>No logo is uploaded</p>-->
          <!--  {% endif %}-->
          <!--</div>-->
          <div class="info">
            <a href="" class="d-block">{{ school }}</a>
          </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
            
            <li class="nav-item">
              {% url 'users:principal_home' as principal_home %}
              <a href="{{ principal_home }}" class="nav-link {% if request.path == principal_home %} active {% endif %}">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                  Home
                  {% comment %} <span class="right badge badge-danger">New</span> {% endcomment %}
                </p>
              </a>
            </li>

            <li class="nav-item">
              {% url 'users:principal_feedback' as principal_feedback %}
              <a href="{{ principal_feedback }}" class="nav-link {% if request.path == principal_feedback %} active {% endif %}">
                <i class="nav-icon fas fa-comments"></i>
                <p>
                  Send Feedback
                  {% comment %} <span class="right badge badge-danger">New</span> {% endcomment %}
                </p>
              </a>
            </li>

            <li class="nav-item">
              {% url 'users:pleaderboard' as pboard %}
              <a href="{{ pboard }}" class="nav-link {% if request.path == pboard %} active {% endif %}">
                <i class="nav-icon fa fa-trophy"></i>
                <p>
                  View Leaderboard
                  {% comment %} <span class="right badge badge-danger">New</span> {% endcomment %}
                </p>
              </a>
            </li>

            <li class="nav-item">
              {% url 'users:pstudent_report' as preport %}
              <a href="{{ preport }}" class="nav-link {% if request.path == preport %} active {% endif %}">
                <i class="nav-icon fa fa-file"></i>
                <p>
                  View Report
                </p>
              </a>
            </li>
          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

templates/principal_template/subjects_list.html
{% extends 'principal_template/base_template.html' %}

{% block page_title %}
    Subject List
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Subjects</h3>
                        </div>
                        <div class="card-body">
                           <div class="table-responsive">
                                <table class="table">
                                    <thead class="thead-light">
                                    <tr>
                                        <th>Name</th>
                                        <th>Class</th>
                                    </tr>
                                    </thead>
                                    {% for subject, classes in subjects.items %}
                                    <tr>
                                        <td>{{ subject }}</td>
                                        <td>{{ classes }}</td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
      </section>
  {% endblock main_content %}

{% block custom_js %}

{% endblock custom_js %}