api/urls.py
from django.urls import path,include
from rest_framework import routers
from api.views import StandardViewSet,SubjectViewSet,LessonViewSet,UserViewSet

router=routers.DefaultRouter()
router.register(r'users',UserViewSet)
router.register(r'standards', StandardViewSet, basename='standard')
router.register(r'subjects', SubjectViewSet,basename='subject')
router.register(r'lessons', LessonViewSet,basename='lesson')

urlpatterns = [
    path('', include(router.urls)),
]

lms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('curriculum/', include(('curriculum.urls','curriculum'), namespace='curriculum')),
    path('mechanzo/', include(('mechanzo.urls','mechanzo'),namespace="mechanzo")),
    # path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('ebook/', include(('ebook.urls', 'ebook'), namespace='ebook')),
    path('', include('pwa.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from users.utils import activate
from . import StudentViews
from . import SchoolView,PrincipalView,TeacherView

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('student/', views.StudentSignUpView.as_view(), name="user_student"),
    path('parent/', views.ParentSignUpView.as_view(), name="user_parent"),
    path('teacher/', views.TeacherSignUpView.as_view(), name="user_teacher"),
    path('principal/', views.PrincipalSignUpView.as_view(), name="user_principal"),
    path('school/', views.SchoolSignUpView.as_view(), name="user_school"),
    path('students_registration/',views.register_student_from_excel, name="students_registration"),
    path('download-excel-template/', views.download_excel_template, name='download_excel_template'),
    path('user_login/',views.user_login, name="user_login"),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
    path('success/', views.success_page, name='success_page'),
    path('create_student_project/', views.create_student_project, name='create_student_project'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
                    template_name="registration/password_reset.html"
    ),name="reset_password"),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),name="pasword_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),name="password_reset_complete"),
    path('activate/<uidb64>/<token>/',activate, name="activate"),
    path('editor/',views.editor, name="editor"),
    path('enquiry',views.enquiry, name="enquiry"),
    path('message',views.message, name="message"),
    path('advocacy',views.create_advocacy_visit, name="advocacy"),
    
    # URLS for Student
    path('student_home/', StudentViews.student_home, name="student_home"),
    path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_feedback/', StudentViews.student_feedback, name="student_feedback"),
    path('student_feedback_save/', StudentViews.student_feedback_save, name="student_feedback_save"),
    path('student_profile/', StudentViews.student_profile, name="student_profile"),
    path('student_profile_update/', StudentViews.student_profile_update, name="student_profile_update"),
    path('student_view_result/',StudentViews.student_report, name="student_view_result"),
    path('notification/', StudentViews.notifications, name="notification"),
    path('notification_read/<int:id>/', StudentViews.mark_notification_as_read, name="notification_read"),
    path("student_leaderboard/",StudentViews.leaderboard, name="student_leaderboard"),
    path("subjects/",StudentViews.subjects, name="subjects"),
    path('sstudent_login_activity/', StudentViews.student_login_activity, name='sstudent_login_activity'),
    path('sstudent_activity/<str:user_id>/', StudentViews.student_activity_view, name='sstudent_activity'),
    path('projectsample/', StudentViews.SampleProjectReport, name='projectsample'),
    
    # URLS for School
    path('school_home/', SchoolView.school_home, name="school_home"),
    path('attendance_data/', SchoolView.student_data_view, name="attendance_data"),
    path('attendance_data_post/', SchoolView.student_view_data_post, name="attendance_data_post"),
    path('teachers_list/', SchoolView.display_teachers, name="teachers_list"),
    path('subject_list/', SchoolView.subject_list, name="subject_list"),
    path('school_profile/', SchoolView.school_profile, name="school_profile"),
    path('school_profile_update/', SchoolView.school_profile_update, name="school_profile_update"),
    path('school_feedback/', SchoolView.school_feedback, name="school_feedback"),
    path('school_feedback_save/', SchoolView.school_feedback_save, name="school_feedback_save"),
    path('school_notification/', SchoolView.notifications, name="school_notification"),
    path('school_notification_read/<int:id>/', SchoolView.mark_notification_as_read, name="school_notification_read"),
    path("leaderboard/",SchoolView.leaderboard, name="leaderboard"),
    path("student_report", SchoolView.student_report, name="student_report"),
    path('student_report_gradewise/<int:grade>/<str:section>/', SchoolView.student_report_gradewise, name='student_report_gradewise'),
    path("student_detail_report/<user_id>", SchoolView.student_detail_report, name="student_detail_report"),
    path('student_activity/<str:user_id>/', SchoolView.student_activity_view, name='student_activity'),
    path("advocacy_list_school",SchoolView.advocacy, name="advocacy_list_school"),
    path('get_report/<int:id>/', SchoolView.get_report, name='get_report_school'),
    path('school_macroplanners/', SchoolView.view_macroplanner, name='school_macroplanner'),
    path('school_microplanners/', SchoolView.view_microplanner, name='school_microplanner'),
    path('school_timetable/', SchoolView.view_timetable ,name='school_timetable'),
    path('inventory_list/', SchoolView.inventory ,name='inventory'),
    path('kreativityshow/', SchoolView.kreativityshow ,name='kreativityshow'),
    path('guestsession/', SchoolView.guestsession ,name='guestsession'),
    path("tleaderboard_school/",SchoolView.leaderboard, name="tleaderboard_school"),
    path("competition/",SchoolView.competition, name="competition"),
    path("innovation/",SchoolView.innovation, name="innovation"),
    path("student_performance/",SchoolView.StudentPerformance, name="student_performance"),
    path('school_login_activity/', SchoolView.school_login_activity, name='school_login_activity'),
    
    # URLS for principal
    path('principal_home/', PrincipalView.principal_home, name="principal_home"),
    path('attendance_data/', PrincipalView.student_data_view, name="attendance_data"),
    path('attendance_data_post/', PrincipalView.student_view_data_post, name="attendance_data_post"),
    path('pteachers_list/', PrincipalView.display_teachers, name="pteachers_list"),
    path('psubject_list/', PrincipalView.subject_list, name="psubject_list"),
    path('principal_profile/', PrincipalView.school_profile, name="principal_profile"),
    path('principal_profile_update/', PrincipalView.school_profile_update, name="principal_profile_update"),
    path('principal_feedback/', PrincipalView.school_feedback, name="principal_feedback"),
    path('principal_feedback_save/', PrincipalView.school_feedback_save, name="principal_feedback_save"),
    path('principal_notification/', PrincipalView.notifications, name="principal_notification"),
    path('principal_notification_read/<int:id>/', PrincipalView.mark_notification_as_read, name="principal_notification_read"),
    path("pleaderboard/",PrincipalView.leaderboard, name="pleaderboard"),
    path("pstudent_report", PrincipalView.student_report, name="pstudent_report"),
    path("pstudent_report_gradewise/<str:grade>/", PrincipalView.student_report_gradewise, name="pstudent_report_gradewise"),
    path("pstudent_detail_report/<user_id>", PrincipalView.student_detail_report, name="pstudent_detail_report"),
    
     # URLS for teacher
    path('teacher_home/', TeacherView.teacher_home, name="teacher_home"),
    path('tsubject_list/', TeacherView.subject_list, name="tsubject_list"),
    path('teacher_profile/', TeacherView.teacher_profile, name="teacher_profile"),
    path('teacher_profile_update/', TeacherView.teacher_profile_update, name="teacher_profile_update"),
    path('teacher_feedback/', TeacherView.teacher_feedback, name="teacher_feedback"),
    path('teacher_feedback_save/', TeacherView.teacher_feedback_save, name="teacher_feedback_save"),
    path('teacher_notification/', TeacherView.notifications, name="teacher_notification"),
    path('upload-lesson-plan/', TeacherView.upload_lesson_plan, name='lesson_plan_upload'),
    path('upload_micro_plan/', TeacherView.upload_micro_plan, name='upload_micro_plan'),
    path('macroplanners/', TeacherView.view_macroplanner, name='view_macroplanner'),
    path('microplanners/', TeacherView.view_microplanner, name='view_microplanner'),
    path('download-macroplanner-template/', TeacherView.download_macroplanner_template, name='download_macroplanner_template'),
    path('download-microplanner-template/', TeacherView.download_microplanner_template, name='download_microplanner_template'),
    path('get_report1/<int:id>/', TeacherView.get_report, name='get_report1'),
    path('teacher_notification_read/<int:id>/', TeacherView.mark_notification_as_read, name="teacher_notification_read"),
    path("tleaderboard/",TeacherView.leaderboard, name="tleaderboard"),
    path("tstudent_report", TeacherView.student_report, name="tstudent_report"),
    path("tstudent_report_gradewise/<int:grade>/<str:section>/", TeacherView.student_report_gradewise, name="tstudent_report_gradewise"),
    path("tstudent_detail_report/<user_id>", TeacherView.student_detail_report, name="tstudent_detail_report"),
    path('advocacy_list',TeacherView.advocacy_visit, name="advocacy_list"),
    path('timetable',TeacherView.upload_timetable, name="timetable"),
    path('view_timetable',TeacherView.view_timetable, name="view_timetable"),
    path('kreativityshow2/', TeacherView.kreativityshow ,name='kreativityshow2'),
    path('guestsession2/', TeacherView.guestsession ,name='guestsession2'),
    path("competition2/",TeacherView.competition, name="competition2"),

templates/school/base_template.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ABL Skool- LMS for students to Learn STEM at their own pace</title>
  <link rel="shortcut icon" type="image/x-icon" href="/static/Images/log.png">
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static "jqvmap/jqvmap.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'  %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "overlayScrollbars/css/OverlayScrollbars.min.css" %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "daterangepicker/daterangepicker.css" %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static "summernote/summernote-bs4.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    {% comment %} For Custom CSS {% endcomment %}

    {% block custom_css %}
    {% endblock custom_css %}

</head>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

  <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>
      <h4 style="margin-left: 10px; margin-top: 5px;">School Dashboard</h4>
      <ul class="navbar-nav mx-4">
        <li class="nav-item">
          <a href="{% url 'users:school_notification' %}">
            <input type="image" src="/static/Images/users/notification.png" alt="" style="height:20px; width:20px;">
          </a>
        </li>
      </ul>
      <ul class="navbar-nav " style="margin-left:400px;">
        {% if schoolcontracts %}
            <li class="nav-item">Subscription Start: {{ schoolcontracts.start_date }}&nbsp;&nbsp;&nbsp;</li>
            <li class="nav-item">Subscription End: {{ schoolcontracts.end_date }}</li>
        {% else %}
            <li class="nav-item">No active subscription found.</li>
        {% endif %}
      </ul>
      <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
            <i class="fas fa-cog"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">
            
            <a href="{% url 'users:school_profile' %}" class="dropdown-item">
              <i class="fas fa-user-edit mr-2"></i> Update Profile
            </a>

            <div class="dropdown-divider"></div>
            <a href="{% url 'users:user_logout' %}" class="dropdown-item">
              <i class="fas fa-power-off mr-2"></i> Logout
            </a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
     </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    {% comment %} {% include 'student_template/sidebar_template.html' with user=user id=id %} {% endcomment %}
    {% include 'school/sidebar_template.html' with user=user id=id %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">
                {% block page_title %}
                {% endblock page_title %}
              </h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href=""></a></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      {% block main_content %}
      {% endblock main_content %}
      <!-- /.content -->
    </div>

    
  </div>
  <!-- ./wrapper -->


<!-- jQuery -->
<script src="{% static "jquery/jquery.min.js"  %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "jquery-ui/jquery-ui.min.js"  %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js"  %}"></script>
<!-- ChartJS -->
<script src="{% static "chart.js/Chart.min.js"  %}"></script>
<!-- Sparkline -->
<script src="{% static "sparklines/sparkline.js"  %}"></script>
<!-- JQVMap -->
<script src="{% static "jqvmap/jquery.vmap.min.js"  %}"></script>
<script src="{% static "jqvmap/maps/jquery.vmap.usa.js"  %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "jquery-knob/jquery.knob.min.js"  %}"></script>
<!-- daterangepicker -->
<script src="{% static "moment/moment.min.js"  %}"></script>
<script src="{% static "daterangepicker/daterangepicker.js"  %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"  %}"></script>
<!-- Summernote -->
<script src="{% static "summernote/summernote-bs4.min.js"  %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "overlayScrollbars/js/jquery.overlayScrollbars.min.js"  %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'  %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js'  %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js'  %}"></script>

{% comment %} For Custom JS {% endcomment %}
{% block custom_js %}
{% endblock custom_js %}

</body>
</html>

templates/school/notification.html
{% extends 'school/base_template.html' %}
{% block page_title %}
Notification
{% endblock page_title %}
{% block main_content %}
    {% for notification in notifications %}
    {% if not notification.read %}
        <ul>
            {% comment %} <h3><a href="{% url 'users:student_feedback'%}">{{ notification.message }}</a></h3> {% endcomment %}
            <li><a href="{% url 'users:school_notification_read' notification.id %}">{{ notification.message }}</a></li>
        </ul>
    {% endif %}
    {% endfor %}
{% endblock main_content %}

templates/school/school_login_activity.html
{% extends 'school/base_template.html' %}

{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Student's Activity</h3>
          </div>
          <div class="card-body">
            <form method="GET" class="form-inline mb-3">
              <div class="form-group mr-2">
                <label for="grade" class="mr-2">Grade:</label>
                {{ form.grade }}
              </div>
              <div class="form-group mr-2">
                <label for="section" class="mr-2">Section:</label>
                {{ form.section }}
              </div>
              <button type="submit" class="btn btn-primary">Filter</button>
            </form>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="thead-light">
                  <tr>
                    <th>Login DateTime</th>
                    <th>Student Name</th>
                    <th>Class</th>
                    <th>Section</th>
                    <th>Login Number</th>
                    <th>Student Report</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in activities_with_user_id %}
                  <tr>
                    <td>{{ item.login_activity.login_datetime }}</td>
                    <td>{{ item.login_activity.get_student_name }}</td>
                    <td>{{ item.login_activity.get_grade }}</td>
                    <td>{{ item.login_activity.get_section }}</td>
                    <td>{{ item.login_activity.login_num }}</td>
                    <td>
                      <a href="{% url 'users:student_activity' item.user_id %}">Get Report</a>
                    </td>
                  </tr>
                  {% empty %}
                  <tr>
                    <td colspan="6">No activities found.</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock main_content %}

templates/school/student_performance.html
{% extends 'school/base_template.html' %}

{% block main_content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Student's Performance</h3>
                    </div>
                    <div class="card-body">
                        <h3>Coming Soon</h3>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
{% endblock main_content %}

{% block js %}

{% endblock js %}

templates/school/student_report.html
{% extends 'school/base_template.html' %}

{% block custom_css %}

{% endblock custom_css %}
{% load static %}

{% block page_title %}
    View Report
{% endblock page_title %}

{% block main_content %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">View Gradewise Report</h3>
                </div>
                <!-- /.card-header -->

                            {% comment %} Display Messages {% endcomment %}
                            {% if messages %}
                            <div class="form-group">
                            <div class="col-12">
                                {% for message in messages %}
                                {% if message.tags == "error" %}
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                {% elif message.tags == "success" %}
                                    <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                            </div>
                            {% endif %}
                        
                    <form method="POST" action="{% url 'users:student_report_gradewise' %}">
                    {% csrf_token %}

                    <div class="card-body">
                        <div class="form-group">
                            <label>Class </label>
                            <select class="form-control" name="grade" id="grade">
                                    <option value="1" name="grade1">Grade 1</option>
                                    <option value="2" name="grade2">Grade 2</option>
                                    <option value="3" name="grade3">Grade 3</option>
                                    <option value="4" name="grade4">Grade 4</option>
                                    <option value="5" name="grae5">Grade 5</option>
                                    <option value="6" name="grade6">Grade 6</option>
                                    <option value="7" name="grade7">Grade 7</option>
                                    <option value="8" name="grade8">Grade 8</option>
                                    <option value="9" name="grade9">Grade 9</option>
                                    <option value="10" name="grade10">Grade 10</option>
                                    <option value="11" name="grade11">Grade 11</option>
                                    <option value="12" name="grde12">Grade 12</option>
                            </select>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary" id="fetch_student">Get data</button>
                    </div>
                    <div class="card-footer" id="student_data">
                    </div> 
                </div>
                </form>
                <!-- /.card -->
            </div>
        </div>
    </div><!-- /.container-fluid -->
  </section>

{% endblock main_content %}

{% block custom_js %}

{% endblock custom_js %}

templates/school/student_report_gradewise.html
{% extends 'school/base_template.html' %}

{% block main_content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Students in Grade {{ grade }}</h3>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <form id="search-form1" method="get">
                                <div class="input-group">
                                    <input id="q" type="text" name="q" class="form-control" placeholder="Search by name" value="{{ search_query }}">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        {% if search_query %}
                        <div class="table-responsive">
                            <table class="table table-hover" id="student-grade">
                                <thead class="thead-light">
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Name of Student</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for student in students %}
                                    <tr>
                                        <th>{{ forloop.counter }}</th>
                                        <td>
                                            <a href="{% url 'users:student_detail_report' student.user_id %}" class="student-link">
                                                {{ student.first_name }} {{ student.last_name }}
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% else %}
                        <div class="table-responsive">
                            <table class="table table-hover" id="student-grade">
                                <thead class="thead-light">
                                    <tr>
                                        <th>S.No</th>
                                        <th>Student's Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for student in students %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>
                                            <a href="{% url 'users:student_detail_report' student.user_id %}" class="student-link">
                                                {{ student.first_name }} {{ student.last_name }}
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
{% endblock main_content %}

{% block custom_css %}
<style>
    .student-link {
        /* color: blue; */
        text-decoration: underline;
    }

    .student-link:hover {
        color: darkblue;
    }

    .table-hover tbody tr:hover {
        background-color: #f2f2f2;
    }

    .thead-light {
        background-color: #f8f9fa;
    }
</style>
{% endblock custom_css %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        // Function to update the table with search results
        function updateTable(searchQuery) {
            $.ajax({
                url: window.location.pathname,
                type: 'GET',
                data: { search: searchQuery },
                dataType: 'json',
                success: function (data) {
                    var tableBody = $('#student-grade tbody');
                    tableBody.empty();

                    if (data.students.length === 0) {
                        tableBody.append('<tr><td colspan="2">No results found</td></tr>');
                    } else {
                        $.each(data.students, function (index, student) {
                            tableBody.append('<tr><td>' + (index + 1) + '</td><td><a href="' + data.detail_report_url + student.user_id + '" class="student-link">' + student.first_name + ' ' + student.last_name + '</a></td></tr>');
                        });
                    }
                }
            });
        }

        // Handle form submission
        $('#search-form1').on('submit', function (e) {
            e.preventDefault();
            var searchQuery = $('#q').val();
            updateTable(searchQuery);
        });

        // Initialize the table on page load
        var initialSearchQuery = '{{ search_query }}';
        updateTable(initialSearchQuery);
    });
</script>
{% endblock js %}